exec-once = hyprpm enable hyprbars

plugin {
    hyprbars {
        bar_height = 25
        bar_blur = true
        bar_buttons_alignment = left
        bar_color = rgba(363a4fff)
        bar_text_font = JetBrainsMono NerdFont
        bar_text_size = 12
        col.text = rgba(cad3f5ff)

        bar_button_padding = 8

        bar_part_of_window = false
        icon_on_hover = true

        hyprbars-button = rgba(ed8796ff), 16, , hyprctl dispatch killactive
        hyprbars-button = rgba(7dc4e4ff), 16, , hyprctl dispatch fullscreen 1

    }
}
