windowrule {
    name = hide-bar-as-needed
    match:class = ^(kitty|firefox|steam)$
    hyprbars:no_bar = on
}

windowrule {
    name = no-tile
    match:class = ^(yad|Video Editor|org.kde.kdenlive|kdenlive)$

    float = true
}

windowrule {
    name = kitty-sys-update-dialogue
    match:title = System Update

    float = true
    size = 1280 720
}

windowrule {
    name = discord-with-caelestia
    match:class = discord
    hyprbars:no_bar = on

    border_color = rgb(24273a) 
}

windowrule {
    name = qutebrowser
    match:class = org.qutebrowser.qutebrowser

}
