#############
### BINDS ###
#############

$mod1 = ALT

bind = $mod1 SHIFT, D, togglespecialworkspace, discord

###############
### STARTUP ###
###############

exec-once = [workspace special:discord silent] discord


#############
### RULES ###
#############

windowrule {
	name = discord-scratchpad
	match:class = discord
	workspace = special:discord silent

	float = true
	size = 1200 800
	center = true
}
