include ./current-theme.conf
font_family			JetBrainsMono Nerd Font
font_size 			12.0
background_opacity 1	
window_border_radius 10

window_padding_width 8

map ctrl+shift+j previous_tab
map ctrl+shift+k next_tab

repaint_delay 6
input_delay 0
sync_to_monitor yes

pixel_scroll yes

disable_ligatures cursor

cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 1


tab_bar_edge top
tab_bar_style separator
tab_separator " │ "
active_tab_font_style bold
inactive_tab_font_style normal
