#!/usr/bin/env bash
log_path='/home/addigoat/Projects/Engines/Kristal/kristal.log'
echo "-----clear-----" > $log_path 
stdbuf -oL -eL /usr/bin/love /home/addigoat/Projects/Engines/Kristal/ >> $log_path 2>&1
