#!/usr/bin/env fish

set -l noteDir "$HOME/Sync/Documents/Obsidian/MainVault/100 - Index"

if not test -e $noteDir then
    set noteDir "$HOME/Notes"
    mkdir -p $noteDir
end

set -l prompt "+ New Note"


set -l choice (
begin
  echo "$prompt"
  for note in "$noteDir"/*.md
    echo (basename "$note")
  end
end | rofi -dmenu -p "Notes"
)

switch $choice
  case "$prompt"
    set name (rofi -dmenu -p "Name")
    test -z $name; and exit 0
    set target "$noteDir/$name.md"
    touch $target
    kitty --class rofi-notes nvim "$target"
  case ""
    echo "User exited launcher"; exit 0
  case "*"
  set noteChoice (printf "%s\n" "View" "Edit" "Delete" | rofi -dmenu)
  switch $noteChoice
    case "View"
      kitty --title kitty-float glow -t "$noteDir/$choice"
    case "Edit"
      kitty --title kitty-float nvim "$noteDir/$choice"
    case "Delete"
      set confirm (printf "%s\n" "Yes" "No" | rofi -dmenu)
      if test "$confirm" = "Yes"
        rm "$noteDir/$choice"
        exit 0
      else
        exit 0
      end
  end
end



