#!/usr/bin/env fish

set -l noteDir "$HOME/Sync/Documents/Obsidian/MainVault/100 - Index"

if not test -e $noteDir then
    set noteDir "$HOME/Notes"
    mkdir -p $noteDir
end

set -l prompt "+ New Note"


set -l choice (
begin
  echo "$prompt"
  for note in "$noteDir"/*.md
    echo (basename "$note")
  end
end | rofi -dmenu -p "Notes"
)

switch $choice

    # New Note Choice
    case "$prompt"
        set file_name (rofi -dmenu -p "Name")

        test -z $file_name; and exit 0

        make_note $file_name $write_dir

        kitty --class rofi-notes nvim "$write_dir/$file_name.md"

    case ""
        echo "User exited launcher"; exit 0

    # Chose existing note
    case "*"

        set note_action (printf "%s\n" "View" "Edit" "Delete" | rofi -i -dmenu)

        switch $note_action
            case "View"
                kitty --title kitty-float glow -t "$read_dir/$choice"

            case "Edit"
                kitty --title kitty-float nvim "$read_dir/$choice"

            case "Delete"
                set confirm (printf "%s\n" "Yes" "No" | rofi -i -dmenu)

                if test "$confirm" = "Yes"
                    rm "$read_dir/$choice"
                    exit 0
                else
                    exit 0
                end
        end
end



