#!/usr/bin/env fish

set -l read_dir "$HOME/Sync/Documents/Obsidian/MainVault/"
set -l write_dir "$read_dir/100 - Index"

set -l prompt "+ New Note"

if not test -e $read_dir
    set read_dir "$HOME/Notes"
    set write_dir "$read_dir"
end

mkdir -p $write_dir


function title_case
    for word in (string split '-' $argv[1])
        set first (string upper (string sub -l 1 $word))
        set rest (string sub -s 2 $word)
        echo -n "$first$rest "
    end
end

function make_note -a name dir
    set -f pretty_name (title_case "$name")
    printf "\n\n\n%s" (date +"%a, %B %-d, %Y - %I:%M %p") >> "$dir/$name.md"
end

set -l choice (
begin
    echo "$prompt"
    for note in (cd "$read_dir"; fd . -e md)
        echo "$note"
    end
end | rofi -dmenu -i -p "notes:"
)

switch $choice

    # New Note Choice
    case "$prompt"
        set file_name (rofi -dmenu -p "name:")

        if test -z $file_name
            set file_name (date +%Y-%m-%d_%H-%M-%S)
        end

        make_note "$file_name" "$write_dir"

        kitty --class rofi-notes nvim "$write_dir/$file_name.md"

    case ""
        echo "User exited launcher"; exit 0

    # Chose existing note
    case "*"

        set note_action (printf "%s\n" "View" "Edit" "Delete" | rofi -i -dmenu)

        switch $note_action
            case "View"
                kitty --title kitty-float glow -t "$read_dir/$choice"

            case "Edit"
                kitty --title kitty-float nvim "$read_dir/$choice"

            case "Delete"
                set confirm (printf "%s\n" "Yes" "No" | rofi -i -dmenu)

                if test "$confirm" = "Yes"
                    rm "$read_dir/$choice"
                    exit 0
                else
                    exit 0
                end
        end
end



