wallpaper {
	monitor = DP-2
	path = ~/.config/Wallpapers/Addi.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/.config/Wallpapers/Addi.png
	fit_mode = cover
}

splash = false
ipc = off
