#!/usr/bin/env bash

PROJECT_DIR="$HOME/projects/code"

project=$(find "$PROJECT_DIR" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | sort | rofi -dmenu -i -p "Code")
[ -z "$project" ] && exit

fullpath="$PROJECT_DIR/$project"

action=$(printf "VSCode\nKitty shell here\nRanger in Kitty\n" | rofi -dmenu -i -p "Open $project with")
[ -z "$action" ] && exit

case "$action" in
    "VSCode")
        code "$fullpath"
        ;;
    "Kitty shell here")
        kitty --directory "$fullpath"
        ;;
    "Ranger in Kitty")
        kitty --directory "$fullpath" ranger
        ;;
esac
