#!/bin/bash

confirm_action() {
	printf "%s\n" "No" "Yes" | rofi -dmenu -i -p "$1"
}

choice=$(printf "%s\n" " Lock" "󰍃 Logout" "󰤄 Suspend" "󰜉 Reboot" "󰐥 Shutdown" | rofi -dmenu -i)

case "$choice" in
	" Lock")
		hyprlock
		;;
	"󰍃 Logout")
		hyprshutdown
		;;
	"󰤄 Suspend")
		systemctl suspend
		;;
	"󰜉 Reboot")
		confirm=$(confirm_action "Reboot?")
		case "$confirm" in
			Yes)
				systemctl reboot
				;;
			*)
				exit
				;;
		esac
		;;
	"󰐥 Shutdown")
		confirm=$(confirm_action "Shutdown?")
		case "$confirm" in
			Yes)
				systemctl poweroff
				;;
			*)
				exit
				;;
		esac
		;;
	*)
		exit
		;;
esac


