#!/usr/bin/env bash

choice=$(printf "%s\n" "ChatGPT" "GitHub" "Cloudflare" "iLearn" "Google" "Youtube" "Catppuccin Palette" "DevDocs" | rofi -dmenu -i)

case "$choice" in
	"ChatGPT")
		gtk-launch chatgpt.desktop
		;;
	"GitHub")
		xdg-open "https://github.com/addiGoat?tab=repositories"
		;;
    "Cloudflare")
        xdg-open "https://dash.cloudflare.com/fc028d4ce32f18cb01120d766a58ac30/addigoat.ca"
        ;;
	"iLearn")
		xdg-open "https://ilearn.canadorecollege.ca"
		;;
	"Google")
		xdg-open "https://www.google.com/"
		;;
	"Catppuccin Palette")
		xdg-open "https://catppuccin.com/palette/"
		;;
	"Youtube")
		xdg-open "https://www.youtube.com/"
		;;
	"DevDocs")
		xdg-open "https://devdocs.io/"
		;;
esac
